require("codeyman2.plugins-setup")
require("codeyman2.core.options")
require("codeyman2.core.keymaps")
-- require("codeyman2.core.colorscheme-rose")
require("codeyman2.core.colorscheme-seoul")
-- require("codeyman2.core.colorscheme-zenbones")
require("codeyman2.plugins.comment")
require("codeyman2.plugins.nvim-tree")
require("codeyman2.plugins.lualine")
require("codeyman2.plugins.treesitter")
-- require("codeyman2.plugins.lsp")
require("codeyman2.plugins.nvim-transparent")
-- require("codeyman2.plugins.telescope")
require("codeyman2.plugins.nvim-cmp")
require("codeyman2.plugins.lsp.mason")
require("codeyman2.plugins.lsp.lspsaga")
require("codeyman2.plugins.lsp.lspconfig")
require("codeyman2.plugins.lsp.null-ls")
require("codeyman2.plugins.autopairs")
require("codeyman2.plugins.gitsigns")
require("codeyman2.plugins.nvim-ufo")
